#! /bin/sh

set -u
set -e
set -x

# Extract the usage from the markdown
cat README.md | \
  awk '/```/{ cnt+=1; } { if ( cnt == 1 && $1 != "```" ) { print "printf(\"" $0 "\\n\");" } }' > help.inc

# Build man page if pandoc is installed
if which pandoc 2> /dev/null
then
	pandoc -f markdown -s -t man -o asymcrypt.1 README.md
	pandoc -f markdown -s -t man -o asymcrypt_formats.5 asymcrypt_formats.5.md
fi

# Build command
gcc $(pkg-config libsodium --cflags --libs) -g -Wfatal-errors -Wall --pedantic --std=c99 -O2 main.c -o asymcrypt